version: "3.9"
services:
  geth:
    image: docker.gbre.org/geth
    init: true
    build: ./geth
    user: 1000:1000
    ports:
      - 30303
      - 8544:8545
      - 8551
    volumes:
      - /mnt/Scorpion/abi-cluster/main/geth-data:/home/ethereum/.ethereum
      - /mnt/Scorpion/abi-cluster/main/geth-keystore:/home/ethereum/.keystore
    command: --http --http.addr 0.0.0.0 --http.vhosts localhost,geth --keystore ~/.keystore --allow-insecure-unlock --authrpc.addr 0.0.0.0 --authrpc.vhosts localhost,geth
    # command: --http --http.addr 0.0.0.0 --http.vhosts localhost,geth --keystore ~/.keystore --allow-insecure-unlock snapshot prune-state
    restart: unless-stopped
    stop_grace_period: 5m

  beacon:
    image: docker.gbre.org/lighthouse
    init: true
    build: ./lighthouse
    user: 1000:1000
    ports:
      - 9000:9000
      - 9000:9000/udp
      - 5052:5052
    volumes:
      - /mnt/Scorpion/abi-cluster/main/lighthouse-data:/home/lighthouse/.lighthouse
      - /mnt/Scorpion/abi-cluster/main/geth-data:/home/lighthouse/.ethereum
    command: beacon_node --staking --http-address 0.0.0.0 --subscribe-all-subnets --import-all-attestations --validator-monitor-auto --execution-endpoint http://geth:8551 --execution-jwt /home/lighthouse/.ethereum/geth/jwtsecret --suggested-fee-recipient $SUGGESTED_FEE_RECIPIENT --monitoring-endpoint https://beaconcha.in/api/v1/client/metrics?apikey=$BEACONCHAIN_API_KEY
    restart: unless-stopped
    stop_grace_period: 5m

  validator:
    image: docker.gbre.org/lighthouse
    init: true
    build: ./lighthouse
    user: 1000:1000
    ports:
      - 5062:5062
    volumes:
      - /mnt/Scorpion/abi-cluster/main/lighthouse-keystore:/home/lighthouse/.lighthouse
    command: validator_client --http --beacon-nodes http://beacon:5052 --graffiti-file /home/lighthouse/.lighthouse/mainnet/graffiti_file.txt --monitoring-endpoint https://beaconcha.in/api/v1/client/metrics?apikey=$BEACONCHAIN_API_KEY
    restart: unless-stopped
    stop_grace_period: 5m
